"""
Build the investor deck as a real PowerPoint file.

    py pitch-deck.py        ->  Air-Debt.pptx

A SCRIPT RATHER THAN A FILE, for the same reason the art is generated by scripts
rather than drawn: a deck is full of numbers that go stale — the air ceiling, the
test count, what a careful clear costs — and a .pptx is a zip nobody is going to
open and correct. This reads the real figures where it can and keeps the rest in
one block at the top, so bringing the deck up to date is running it again.

The design is the game's, deliberately: the palette is lifted from
`src/app/globals.css`, the display face is monospace because the HUD is
monospace, and the slides are dark because the game is. It is the same system as
`pitch.html`, in a format that opens on somebody else's laptop with no internet.
"""

import pathlib
import subprocess
import sys

try:
    from pptx import Presentation
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    from pptx.util import Emu, Inches, Pt
except ImportError:
    sys.exit("python-pptx is missing.  py -m pip install python-pptx")

HERE = pathlib.Path(__file__).parent
SHOTS = HERE / "public" / "shots"
OUT = HERE / "Air-Debt.pptx"

# --------------------------------------------------------------------- palette
# The game's own, from src/app/globals.css.
GROUND = RGBColor(0x0B, 0x0E, 0x14)
SURFACE = RGBColor(0x10, 0x15, 0x1D)
EDGE = RGBColor(0x1C, 0x25, 0x31)
AIR = RGBColor(0x5F, 0xD9, 0xCF)  # time left, alive, breathing
BRASS = RGBColor(0xFF, 0xD1, 0x66)  # gems, gold, what you carried back
WARN = RGBColor(0xE5, 0x6B, 0x6F)  # the clock under ten seconds
TEXT = RGBColor(0xE7, 0xEC, 0xF2)
MUTED = RGBColor(0x8A, 0x94, 0xA6)
DIM = RGBColor(0x6B, 0x7A, 0x89)

MONO = "Consolas"
SANS = "Segoe UI"

W, H = Inches(13.333), Inches(7.5)  # 16:9
M = Inches(0.85)  # the margin everything hangs off

# ----------------------------------------------------------------- the numbers
# Measured from the repository and from real play. Anything here that becomes
# untrue should be corrected here and the script re-run.
FACTS = {
    "url": "air-debt-game.vercel.app",
    "environments": 5,
    "enemies": 12,
    "shop_items": 30,
    "unit_tests": 292,
    "browser_tests": 16,
    "art_frames": 168,
    "base_air": 30,
    "max_air_min": "3.5",
    "clear_direct": 141,
    "clear_careful": 205,
    "margin": 5,
}


def solid(shape, colour):
    shape.fill.solid()
    shape.fill.fore_color.rgb = colour
    shape.line.fill.background()


def box(slide, x, y, w, h, colour=None, line=None):
    from pptx.enum.shapes import MSO_SHAPE

    s = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, x, y, w, h)
    if colour is None:
        s.fill.background()
    else:
        s.fill.solid()
        s.fill.fore_color.rgb = colour
    if line is None:
        s.line.fill.background()
    else:
        s.line.color.rgb = line
        s.line.width = Pt(1)
    s.shadow.inherit = False
    return s


def text(
    slide,
    body,
    x,
    y,
    w,
    h,
    size=18,
    colour=TEXT,
    font=SANS,
    bold=False,
    spacing=0,
    align=PP_ALIGN.LEFT,
    leading=1.25,
    link=None,
    underline=False,
):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    for i, line in enumerate(body.split("\n")):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = leading
        r = p.add_run()
        r.text = line
        r.font.size = Pt(size)
        r.font.color.rgb = colour
        r.font.name = font
        r.font.bold = bold
        r.font.underline = underline
        if link:
            # A real hyperlink, so it is clickable in the slideshow rather than
            # a URL somebody has to type out while everyone watches.
            r.hyperlink.address = link
            # PowerPoint recolours hyperlinks to the theme's link colour unless
            # the run's own colour is reasserted after the link is set.
            r.font.color.rgb = colour
        if spacing:
            # python-pptx has no letter-spacing API; set it on the XML.
            r.font._rPr.set("spc", str(int(spacing * 100)))
    return tb


def slide(prs, eyebrow=None, eyebrow_colour=AIR):
    s = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    bg = box(s, 0, 0, W, H, GROUND)
    bg.shadow.inherit = False
    if eyebrow:
        text(
            s,
            eyebrow.upper(),
            M,
            Inches(0.62),
            Inches(9),
            Inches(0.3),
            size=11,
            colour=eyebrow_colour,
            font=MONO,
            bold=True,
            spacing=2.6,
        )
    return s


def heading(s, body, y=Inches(1.12), size=34, colour=TEXT, w=Inches(11.6)):
    return text(s, body, M, y, w, Inches(1.6), size=size, colour=colour, font=MONO, bold=True, leading=1.1)


def rule(s, y, w=Inches(11.6)):
    box(s, M, y, w, Emu(9525), EDGE)


def footer(s, n):
    text(
        s,
        f"AIR DEBT  ·  {FACTS['url']}",
        M,
        H - Inches(0.62),
        Inches(7),
        Inches(0.3),
        size=9,
        colour=DIM,
        font=MONO,
        spacing=1.8,
    )
    text(
        s,
        f"{n:02d}",
        W - M - Inches(1),
        H - Inches(0.62),
        Inches(1),
        Inches(0.3),
        size=9,
        colour=DIM,
        font=MONO,
        align=PP_ALIGN.RIGHT,
    )


def fade(s, ms=450):
    """
    A short cross-fade onto this slide.

    python-pptx has no transition API, so the element is written into the slide's
    XML directly. The schema puts `p:transition` after `p:clrMapOvr` and before
    `p:timing`, and PowerPoint is strict about that order — appended anywhere else
    the file opens with a repair prompt, which is the worst possible thing to
    happen to a deck in front of somebody.

    A fade and nothing else, deliberately. Every other transition PowerPoint
    offers announces itself, and an effect the audience notices is an effect that
    took their attention off the slide. This one is only there so a slide arrives
    rather than snapping.
    """
    from pptx.oxml.ns import qn

    sld = s._element
    for existing in sld.findall(qn("p:transition")):
        sld.remove(existing)

    tr = sld.makeelement(qn("p:transition"), {"spd": "med", "advClick": "1"})
    tr.append(sld.makeelement(qn("p:fade"), {}))

    # After clrMapOvr if it is there, otherwise straight after cSld.
    anchor = sld.find(qn("p:clrMapOvr")) if sld.find(qn("p:clrMapOvr")) is not None else sld.find(qn("p:cSld"))
    anchor.addnext(tr)
    return tr


def picture(s, name, x, y, w):
    """A screenshot, with a hairline so it does not float on the dark."""
    f = SHOTS / name
    if not f.exists():
        return None
    pic = s.shapes.add_picture(str(f), x, y, width=w)
    box(s, x, y, pic.width, pic.height, None, EDGE)
    return pic


# =========================================================================== 01
prs = Presentation()
prs.slide_width, prs.slide_height = W, H

s = slide(prs)
text(s, "AIR DEBT", M, Inches(2.2), Inches(9), Inches(1.4), size=66, colour=TEXT, font=MONO, bold=True, spacing=-1)
text(
    s,
    "Thirty seconds of air — and every second you spend\ndown there is a second you need to get back.",
    M,
    Inches(3.42),
    Inches(9.4),
    Inches(1.1),
    size=22,
    colour=TEXT,
    font=SANS,
    leading=1.35,
)
text(
    s,
    "Walk out and everything you are carrying is yours. Don't, and none of it was.",
    M,
    Inches(4.72),
    Inches(9.4),
    Inches(0.5),
    size=15,
    colour=MUTED,
)
rule(s, Inches(5.35))
text(
    s,
    f"PLAYABLE NOW  ·  {FACTS['url']}",
    M,
    Inches(5.6),
    Inches(8),
    Inches(0.35),
    size=12,
    colour=AIR,
    font=MONO,
    bold=True,
    spacing=2,
    link=f"https://{FACTS['url']}",
)
text(s, "Built by one person  ·  Web  ·  Next.js and Postgres", M, Inches(6.05), Inches(8), Inches(0.35), size=12, colour=DIM, font=MONO, spacing=1.4)
footer(s, 1)

# =========================================================================== 02
s = slide(prs, "The loop")
heading(s, "Every second you spend down there\nis a second you need to get back.")
text(
    s,
    "Most games with a timer use it to hurry you. This one uses it to make you wrong.\n"
    "The air is the only resource, and it is spent on everything at once: the fight, the\n"
    "chest, and the walk home.",
    M,
    Inches(2.7),
    Inches(11.4),
    Inches(1.4),
    size=16,
    colour=MUTED,
    leading=1.45,
)
text(
    s,
    "So the game is not really about combat. It is about a decision made with a number\n"
    "in the corner of your eye — I have eleven seconds, and the shaft is four seconds\n"
    "behind me, so this chest is not mine.",
    M,
    Inches(4.0),
    Inches(11.4),
    Inches(1.4),
    size=16,
    colour=TEXT,
    leading=1.45,
)
cols = [
    ("Go down", "Five environments, fixed geometry,\nreshuffled encounters. Deeper stone\nis worth more."),
    ("Take what you can", "Gems and gold out of chests and\nmonsters. Everything is carried,\nnothing is banked."),
    ("Get out", "Any exit banks the whole bag.\nDying or suffocating loses all of it\n— and only it."),
]
cw = Inches(3.6)
for i, (t_, b_) in enumerate(cols):
    x = M + i * (cw + Inches(0.2))
    box(s, x, Inches(5.3), cw, Inches(1.3), SURFACE, EDGE)
    text(s, t_, x + Inches(0.22), Inches(5.46), cw, Inches(0.3), size=13, colour=BRASS, font=MONO, bold=True)
    text(s, b_, x + Inches(0.22), Inches(5.8), cw - Inches(0.4), Inches(0.72), size=11, colour=DIM, leading=1.3)
footer(s, 2)

# =========================================================================== 03
s = slide(prs, "The design")
heading(s, "The biggest tank you can buy\nis deliberately not enough.")
text(
    s,
    f"{FACTS['base_air']} seconds to start. Ten upgrades take it to {FACTS['max_air_min']} minutes, and {FACTS['max_air_min']} minutes still will\n"
    "not walk the whole dungeon and beat the boss. That is not a balance problem — it\n"
    "is the point.",
    M,
    Inches(2.7),
    Inches(11.4),
    Inches(1.3),
    size=16,
    colour=MUTED,
    leading=1.45,
)
box(s, M, Inches(4.15), Inches(11.6), Inches(1.05), SURFACE, EDGE)
text(
    s,
    f"Measured on a full tank with every shortcut open:  a direct clear takes {FACTS['clear_direct']}s,\n"
    f"a careful clear taking every chest takes {FACTS['clear_careful']}s — {FACTS['margin']} seconds inside the ceiling.",
    M + Inches(0.3),
    Inches(4.38),
    Inches(11),
    Inches(0.7),
    size=14,
    colour=AIR,
    font=MONO,
    leading=1.4,
)
text(
    s,
    "Closing the gap needs SHORTCUTS, and a shortcut only opens from a lever placed past\n"
    "the ground it skips. So progress cannot be bought, cannot be rushed, and cannot be\n"
    "learned from a walkthrough — you have to have been there.",
    M,
    Inches(5.4),
    Inches(11.4),
    Inches(1.15),
    size=15,
    colour=MUTED,
    leading=1.4,
)
footer(s, 3)

# =========================================================================== 04
s = slide(prs, "Five environments")
heading(s, "Hardest last, and each one\ntakes something away from you.", size=30)
envs = [
    ("01", "Parkour", "No monsters at all. It teaches you to move."),
    ("02", "Poison", "Green fire and things that chase. Read the room before entering."),
    ("03", "Water", "A flooded cave modelled on a real one. It takes the floor away and gives you a second clock: five breaths."),
    ("04", "Rock", "Something stands in the doorway with two archers strapped to its shoulders."),
    ("05", "Fire", "Where the clock beats you. At the bottom, a boss built from your own move set."),
]
y = Inches(2.75)
for n, name, what in envs:
    box(s, M, y, Inches(6.4), Inches(0.72), SURFACE, EDGE)
    text(s, n, M + Inches(0.2), y + Inches(0.1), Inches(0.5), Inches(0.3), size=11, colour=DIM, font=MONO, bold=True)
    text(s, name, M + Inches(0.75), y + Inches(0.07), Inches(1.6), Inches(0.3), size=13, colour=TEXT, font=MONO, bold=True)
    text(s, what, M + Inches(0.75), y + Inches(0.36), Inches(5.4), Inches(0.35), size=10, colour=DIM, leading=1.15)
    y += Inches(0.79)
picture(s, "cenote.png", M + Inches(6.9), Inches(2.75), Inches(4.7))
text(
    s,
    "The water: rock closes over your head and the only air\nis the shafts of daylight.",
    M + Inches(6.9),
    Inches(5.35),
    Inches(4.7),
    Inches(0.6),
    size=11,
    colour=DIM,
    leading=1.3,
)
footer(s, 4)

# =========================================================================== 05
s = slide(prs, "Safety", BRASS)
heading(s, "A score is never sent to us.\nThe keystrokes are.")
text(
    s,
    "Leaderboards and an in-game economy are the two things players cheat, and the two\n"
    "things worth asking about first. This is the whole mechanism.",
    M,
    Inches(2.65),
    Inches(11.4),
    Inches(0.8),
    size=15,
    colour=MUTED,
    leading=1.4,
)
steps = [
    ("01", "The server opens the run", "It issues the seed — which decides the entire layout — and writes down the tank and the equipment before a single frame is played."),
    ("02", "You play; the game records the keys", "Not positions, not scores. Which keys were held on which tick. The simulation is a deterministic function of exactly that."),
    ("03", "The server replays it", "Through the same code, from the conditions it wrote down itself, and works out what happened."),
    ("04", "The result is credited from the replay", "Both the leaderboard score and the loot. No request in the game adds to a balance by asking."),
]
y = Inches(3.35)
for i, (n, t_, b_) in enumerate(steps):
    fill = RGBColor(0x0D, 0x1A, 0x19) if i == 3 else SURFACE
    box(s, M, y, Inches(11.6), Inches(0.66), fill, EDGE)
    text(s, n, M + Inches(0.22), y + Inches(0.22), Inches(0.5), Inches(0.3), size=11, colour=BRASS if i == 3 else AIR, font=MONO, bold=True)
    text(s, t_, M + Inches(0.8), y + Inches(0.09), Inches(4.2), Inches(0.3), size=12, colour=TEXT, font=MONO, bold=True)
    text(s, b_, M + Inches(0.8), y + Inches(0.36), Inches(10.4), Inches(0.28), size=10, colour=DIM, leading=1.15)
    y += Inches(0.72)
text(
    s,
    "To cheat, you would have to submit keystrokes that genuinely produce the score.\nThat is not cheating. That is playing.",
    M,
    Inches(6.12),
    Inches(11.4),
    Inches(0.5),
    size=14,
    colour=AIR,
    font=MONO,
    bold=True,
    leading=1.3,
)
footer(s, 5)

# =========================================================================== 06
s = slide(prs, "Where it is")
heading(s, "All of this is running today,\nat a public address.")
figs = [
    (FACTS["environments"], "Environments"),
    (FACTS["enemies"], "Enemy types"),
    (FACTS["shop_items"], "Shop items"),
    (FACTS["unit_tests"], "Simulation tests"),
    (FACTS["browser_tests"], "Browser tests"),
    (FACTS["art_frames"], "Art frames, generated"),
]
fw = Inches(1.85)
for i, (n, label) in enumerate(figs):
    x = M + i * (fw + Inches(0.08))
    box(s, x, Inches(2.75), fw, Inches(1.15), SURFACE, EDGE)
    text(s, str(n), x + Inches(0.18), Inches(2.92), fw, Inches(0.5), size=26, colour=BRASS, font=MONO, bold=True)
    text(s, label.upper(), x + Inches(0.18), Inches(3.45), fw - Inches(0.2), Inches(0.3), size=8, colour=DIM, font=MONO, spacing=1.4)
picture(s, "board.png", M, Inches(4.15), Inches(5.0))
text(
    s,
    "THE ART IS GENERATED, NOT LICENSED.",
    M + Inches(6.1),
    Inches(4.25),
    Inches(5.5),
    Inches(0.3),
    size=11,
    colour=AIR,
    font=MONO,
    bold=True,
    spacing=1.4,
)
text(
    s,
    "Every sprite comes out of fourteen scripts checked in beside\n"
    "their output, so there is no asset bill and no licence to honour.\n"
    "The sound is the same idea — every noise is synthesised the\n"
    "moment it plays. There is not one audio file in the project.",
    M + Inches(6.1),
    Inches(4.62),
    Inches(5.5),
    Inches(1.1),
    size=12,
    colour=MUTED,
    leading=1.35,
)
text(
    s,
    "INFRASTRUCTURE COSTS EFFECTIVELY NOTHING.",
    M + Inches(6.1),
    Inches(5.95),
    Inches(5.5),
    Inches(0.3),
    size=11,
    colour=AIR,
    font=MONO,
    bold=True,
    spacing=1.4,
)
text(
    s,
    "Stateless serverless and managed Postgres, no always-on\nprocess — chosen so it stays true as players arrive.",
    M + Inches(6.1),
    Inches(6.18),
    Inches(5.5),
    Inches(0.5),
    size=12,
    colour=MUTED,
    leading=1.35,
)
footer(s, 6)

# =========================================================================== 07
s = slide(prs, "What it is not", WARN)
heading(s, "The missing pieces, before you ask.")
text(
    s,
    "A founder who knows what is not built is easier to back than one who does not.\n"
    "This list is also in the public repository, where it has to stay true.",
    M,
    Inches(2.5),
    Inches(11.4),
    Inches(0.8),
    size=15,
    colour=MUTED,
    leading=1.4,
)
gaps = [
    ("NOT BUILT", WARN, "Monetisation", "No payment provider, no checkout. The economy it would sell into is finished and server-owned — which had to be right first, because selling currency on top of an economy the client controls is selling something you do not own."),
    ("NOT BUILT", WARN, "PvP and Survival", "Both are on the menu and marked as coming, so a player can see the shape of the game. Nothing is behind either."),
    ("NOT BUILT", WARN, "Mobile", "Keyboard only. Web first as validation, native after — but that is a plan, not a build."),
    ("EARLY", BRASS, "Players", "It went live this week. The runs on the leaderboard are real, and there are not many of them."),
]
y = Inches(3.5)
for tag, colour, name, what in gaps:
    rule(s, y)
    text(s, tag, M, y + Inches(0.16), Inches(1.4), Inches(0.3), size=9, colour=colour, font=MONO, bold=True, spacing=1.4)
    text(s, name, M + Inches(1.5), y + Inches(0.12), Inches(2.2), Inches(0.3), size=13, colour=TEXT, font=MONO, bold=True)
    text(s, what, M + Inches(3.8), y + Inches(0.12), Inches(7.7), Inches(0.55), size=11, colour=DIM, leading=1.22)
    y += Inches(0.82)
footer(s, 7)

# =========================================================================== 08
s = slide(prs, "What is next")
heading(s, "In this order, and for this reason.")
nexts = [
    ("1v1", "Next", "Two scavengers, one tank of air, the same dungeon. The extraction decision becomes a decision about another person."),
    ("Monetisation", "After 1v1", "Cosmetics and convenience on top of an economy that is already server-authoritative. Deliberately after the economy was made honest, not before."),
    ("Survival, in 3D", "Later", "Hold a map against waves, ranked. A different game sharing the same spine."),
    ("Native mobile", "Later", "The end goal. The web build is the validation stage; the simulation already runs anywhere with a clock."),
]
y = Inches(2.6)
for name, when, what in nexts:
    box(s, M, y, Inches(11.6), Inches(0.92), SURFACE, EDGE)
    text(s, name, M + Inches(0.28), y + Inches(0.14), Inches(3.4), Inches(0.3), size=14, colour=BRASS, font=MONO, bold=True)
    text(s, what, M + Inches(0.28), y + Inches(0.48), Inches(9.2), Inches(0.4), size=11, colour=DIM, leading=1.2)
    text(s, when.upper(), M + Inches(9.9), y + Inches(0.3), Inches(1.5), Inches(0.3), size=10, colour=DIM, font=MONO, spacing=1.4, align=PP_ALIGN.RIGHT)
    y += Inches(1.0)
footer(s, 8)

# =========================================================================== 09
s = slide(prs, "Why partner")
heading(
    s,
    "One person built a deterministic action game\nwith an economy that cannot be edited from a\nbrowser console, and it is live.",
    size=27,
)
text(
    s,
    "The hard part is done, and it is the part that is usually skipped. Most games reach a\n"
    "playable build with a client-trusted economy and discover the problem when money is\n"
    "involved. This one solved it first — which is why the next three things on the list are\n"
    "additions rather than rewrites.",
    M,
    Inches(3.7),
    Inches(11.4),
    Inches(1.6),
    size=16,
    colour=TEXT,
    leading=1.45,
)
text(
    s,
    "What money buys is time and reach: finishing 1v1, standing up payments properly, and\n"
    "putting it in front of players. Everything the product needs in order to charge for\n"
    "something is already true.",
    M,
    Inches(5.15),
    Inches(11.4),
    Inches(1.2),
    size=15,
    colour=MUTED,
    leading=1.4,
)
# No slab behind it. A filled rectangle under a line of text is a button in a
# web page and a smudge in a slideshow — it sat over the sentence rather than
# behind it. The line carries itself, and it is clickable.
text(
    s,
    f"PLAY IT NOW  —  {FACTS['url']}",
    M,
    Inches(6.25),
    Inches(7),
    Inches(0.4),
    size=15,
    colour=AIR,
    font=MONO,
    bold=True,
    spacing=1.2,
    link=f"https://{FACTS['url']}",
    underline=True,
)
footer(s, 9)

# Applied here rather than per-slide, so a slide added later cannot miss it.
for s in prs.slides:
    fade(s)

prs.save(OUT)
print(f"wrote {OUT.name}  ({OUT.stat().st_size // 1024} KB, {len(prs.slides.__iter__.__self__._sldIdLst)} slides)")