/**
 * Sound, synthesised rather than sampled.
 *
 * Every noise in this file is made out of oscillators and filtered noise at the
 * moment it is played. There is not one audio file in the project and there is
 * not going to be, for the same reasons the art is generated by scripts in
 * `art-src/`: nothing to license, nothing to host, nothing to wait for on a slow
 * connection, and a sound is a handful of numbers that can be tuned in the same
 * place the thing that makes it lives.
 *
 * IT HANGS OFF THE EVENT STREAM. The reducer already emits thirty-six events —
 * a parry, a chest, a lever, a shark's bite — and the renderer already switches
 * on them to throw particles. Audio is the same seam read twice, which means the
 * sim never learns that sound exists (ARCH AD-1) and a replay is silent or loud
 * without changing by a single tick.
 *
 * THE BROWSER WILL NOT LET IT START ON ITS OWN. Autoplay policy blocks an
 * AudioContext until a real gesture, so this stays suspended until `resume` is
 * called from a click — which is what pressing Play is.
 */

import type { SimEvent, SimState } from "../sim/index.ts";
import { tuning } from "../config/tuning.ts";
import { themeAt, type Theme } from "../config/dungeon.ts";

/**
 * A voice for each monster.
 *
 * `hit` and `die` used to be one sound for all twelve of them, which meant a
 * crowd was a single texture repeated — you could not tell from listening what
 * you had just struck or what had just died. Each one gets a pitch and a timbre
 * instead: the goblin is a short bark, the warden is a slab of low noise, the
 * bee is a whine, the phoenix is a shriek, and the Revenant is the goblin an
 * octave down and twice as long, because it is meant to read as the same thing
 * grown terrible.
 *
 * `tell` is the important one and it is new. It plays the moment an enemy enters
 * its wind-up, which is the frame the player is supposed to react to — the whole
 * combat design is reading a telegraph and answering it (PRD FR-5), and until now
 * that reading was entirely visual. A tell you can hear is a tell you can answer
 * while looking somewhere else, which is what makes a crowd survivable.
 */
const VOICE: Record<
  string,
  { hit: number; die: number; tell: number; type: OscillatorType; long?: boolean }
> = {
  "enemy.goblin": { hit: 220, die: 180, tell: 340, type: "square" },
  "enemy.archer": { hit: 300, die: 240, tell: 520, type: "triangle" },
  "enemy.bee": { hit: 900, die: 1200, tell: 1500, type: "sawtooth" },
  "enemy.crab": { hit: 260, die: 150, tell: 400, type: "square" },
  "enemy.lizard": { hit: 340, die: 200, tell: 600, type: "sawtooth" },
  "enemy.shark": { hit: 160, die: 90, tell: 240, type: "sawtooth", long: true },
  "enemy.flamer": { hit: 280, die: 170, tell: 460, type: "square" },
  "enemy.phoenix": { hit: 1100, die: 1400, tell: 1800, type: "triangle" },
  "enemy.kiln": { hit: 120, die: 70, tell: 200, type: "sawtooth", long: true },
  "enemy.hollow": { hit: 140, die: 80, tell: 220, type: "sine", long: true },
  "enemy.warden": { hit: 110, die: 60, tell: 180, type: "sawtooth", long: true },
  "enemy.revenant": { hit: 100, die: 52, tell: 150, type: "sawtooth", long: true },
};

/** How far a sound can be from the camera before it is not worth playing. */
const EARSHOT = 900;

export class GameAudio {
  private ctx: AudioContext | null = null;
  private master: GainNode | null = null;
  /** The ambience bed, one layer per environment, cross-faded as you walk. */
  private bed: { gain: GainNode; source: AudioBufferSourceNode } | null = null;
  private bedTheme: Theme | null = null;
  private noiseBuffer: AudioBuffer | null = null;
  private volume = 0.7;
  private muted = false;
  /** Rate limiting, because sixty ticks a second is sixty of anything. */
  private lastAt: Record<string, number> = {};
  private stepPhase = 0;
  private lastAir = Infinity;
  private lastBreath = Infinity;

  /**
   * Built lazily and left suspended.
   *
   * Constructing an AudioContext before a gesture is what produces the console
   * warning everybody ignores; more importantly a suspended context that is
   * never resumed is a game with no sound and no error.
   */
  private wake(): AudioContext | null {
    if (typeof window === "undefined") return null;
    if (!this.ctx) {
      const Ctor =
        window.AudioContext ??
        (window as unknown as { webkitAudioContext?: typeof AudioContext })
          .webkitAudioContext;
      if (!Ctor) return null;
      this.ctx = new Ctor();
      this.master = this.ctx.createGain();
      this.master.gain.value = this.muted ? 0 : this.volume;
      this.master.connect(this.ctx.destination);

      // One second of white noise, reused by everything that needs a hiss: a
      // footstep, a splash, an explosion, wind. Generating it per sound would be
      // forty-four thousand random numbers each time.
      const rate = this.ctx.sampleRate;
      const buf = this.ctx.createBuffer(1, rate, rate);
      const data = buf.getChannelData(0);
      // A cheap deterministic generator rather than Math.random. Nothing here
      // touches the simulation, but a fixed hiss is one less thing that can
      // differ between two runs of the same code.
      let seed = 22222;
      for (let i = 0; i < data.length; i++) {
        seed = (seed * 1103515245 + 12345) & 0x7fffffff;
        data[i] = (seed / 0x3fffffff - 1) * 0.9;
      }
      this.noiseBuffer = buf;
    }
    return this.ctx;
  }

  /** Called from a click. Without this the browser keeps everything silent. */
  resume(): void {
    const ctx = this.wake();
    if (ctx && ctx.state === "suspended") void ctx.resume();
  }

  setVolume(v: number): void {
    this.volume = Math.max(0, Math.min(1, v));
    if (this.master) {
      this.master.gain.value = this.muted ? 0 : this.volume;
    }
  }

  setMuted(on: boolean): void {
    this.muted = on;
    if (this.master) this.master.gain.value = on ? 0 : this.volume;
  }

  destroy(): void {
    this.bed?.source.stop();
    this.bed = null;
    void this.ctx?.close();
    this.ctx = null;
    this.master = null;
  }

  // ------------------------------------------------------------ the primitives

  /** A tone with an envelope. The workhorse — most things here are one or two. */
  private tone(opts: {
    from: number;
    to?: number;
    type?: OscillatorType;
    gain?: number;
    attack?: number;
    decay: number;
    delay?: number;
    /** Detuned copy, for width. */
    fat?: boolean;
  }): void {
    const ctx = this.ctx;
    if (!ctx || !this.master) return;
    const t0 = ctx.currentTime + (opts.delay ?? 0);
    const g = ctx.createGain();
    const peak = opts.gain ?? 0.2;
    const attack = opts.attack ?? 0.004;
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(peak, t0 + attack);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + attack + opts.decay);
    g.connect(this.master);

    const make = (detune: number) => {
      const o = ctx.createOscillator();
      o.type = opts.type ?? "sine";
      o.detune.value = detune;
      o.frequency.setValueAtTime(opts.from, t0);
      if (opts.to !== undefined && opts.to !== opts.from) {
        o.frequency.exponentialRampToValueAtTime(
          Math.max(20, opts.to),
          t0 + attack + opts.decay,
        );
      }
      o.connect(g);
      o.start(t0);
      o.stop(t0 + attack + opts.decay + 0.02);
    };
    make(0);
    if (opts.fat) make(9);
  }

  /** Filtered noise. Everything percussive, wet or windy is made of this. */
  private hiss(opts: {
    decay: number;
    gain?: number;
    type?: BiquadFilterType;
    from: number;
    to?: number;
    q?: number;
    delay?: number;
  }): void {
    const ctx = this.ctx;
    if (!ctx || !this.master || !this.noiseBuffer) return;
    const t0 = ctx.currentTime + (opts.delay ?? 0);
    const src = ctx.createBufferSource();
    src.buffer = this.noiseBuffer;
    src.loop = true;

    const filter = ctx.createBiquadFilter();
    filter.type = opts.type ?? "bandpass";
    filter.frequency.setValueAtTime(opts.from, t0);
    if (opts.to !== undefined) {
      filter.frequency.exponentialRampToValueAtTime(
        Math.max(30, opts.to),
        t0 + opts.decay,
      );
    }
    filter.Q.value = opts.q ?? 1;

    const g = ctx.createGain();
    g.gain.setValueAtTime(opts.gain ?? 0.2, t0);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + opts.decay);

    src.connect(filter);
    filter.connect(g);
    g.connect(this.master);
    src.start(t0);
    src.stop(t0 + opts.decay + 0.02);
  }

  /** Not more than once every `ms`. Sixty ticks a second is sixty of anything. */
  private throttled(key: string, ms: number): boolean {
    const now = this.ctx?.currentTime ?? 0;
    const last = this.lastAt[key] ?? -Infinity;
    if ((now - last) * 1000 < ms) return false;
    this.lastAt[key] = now;
    return true;
  }

  // ------------------------------------------------------------------ the bed

  /**
   * The ambience under everything, one texture per environment.
   *
   * A loop of filtered noise rather than a piece of music: a dungeon with a
   * tune in it is a different game, and the oxygen clock is doing the tension
   * already. What this is for is making the five environments feel like five
   * PLACES — wind up in the parkour, a wet drip in the water, a low roar in the
   * fire — so that walking from one into the next is something you hear.
   */
  private setBed(theme: Theme): void {
    const ctx = this.ctx;
    if (!ctx || !this.master || !this.noiseBuffer) return;
    if (this.bedTheme === theme) return;
    this.bedTheme = theme;

    const now = ctx.currentTime;
    if (this.bed) {
      const old = this.bed;
      old.gain.gain.cancelScheduledValues(now);
      old.gain.gain.setValueAtTime(old.gain.gain.value, now);
      old.gain.gain.linearRampToValueAtTime(0.0001, now + 1.2);
      old.source.stop(now + 1.3);
    }

    const shape: Record<Theme, { freq: number; q: number; gain: number }> = {
      parkour: { freq: 420, q: 0.7, gain: 0.05 },
      poison: { freq: 190, q: 2.4, gain: 0.06 },
      water: { freq: 130, q: 0.5, gain: 0.08 },
      rock: { freq: 90, q: 1.1, gain: 0.05 },
      fire: { freq: 70, q: 0.8, gain: 0.09 },
    };
    const s = shape[theme];

    const src = ctx.createBufferSource();
    src.buffer = this.noiseBuffer;
    src.loop = true;
    const filter = ctx.createBiquadFilter();
    filter.type = "lowpass";
    filter.frequency.value = s.freq;
    filter.Q.value = s.q;
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.0001, now);
    g.gain.linearRampToValueAtTime(s.gain, now + 1.5);
    src.connect(filter);
    filter.connect(g);
    g.connect(this.master);
    src.start(now);
    this.bed = { gain: g, source: src };
  }

  // ---------------------------------------------------------------- the frame

  /**
   * Everything audible about this tick.
   *
   * Takes the state rather than being called from forty places, for the same
   * reason the renderer does: one place that knows what a frame sounds like is
   * one place to change when it sounds wrong.
   */
  frame(state: SimState, previous: SimState, cameraX: number): void {
    if (!this.wake()) return;
    if (this.ctx?.state !== "running") return;

    const near = (x: number) => Math.abs(x - cameraX - 640) < EARSHOT;

    if (state.entered) this.setBed(themeAt(state.player.x));

    // Telegraphs first: the wind-up is the frame the player has to answer, and
    // hearing it is what makes a fight you are not looking directly at
    // survivable. Matched by index because the array is stable within a run.
    for (let i = 0; i < state.enemies.length; i++) {
      const now = state.enemies[i];
      const was = previous.enemies[i];
      if (!was || was.kind !== now.kind) continue;
      if (now.phase === "telegraphing" && was.phase !== "telegraphing") {
        if (near(now.x) && this.throttled(`tell${now.kind}`, 90)) {
          this.tell(now.kind);
        }
      }
    }

    for (const e of state.events) {
      // Worked out before the noise, because the event says where a blow landed
      // and not what it landed on.
      const at = (e as { x?: number; y?: number }).x;
      if (typeof at === "number") {
        this.hitKind = this.nearestKind(
          state,
          at,
          (e as { y?: number }).y ?? 0,
        );
      }
      this.event(e, near);
    }
    this.continuous(state, previous);
  }

  /** The noises that come from state rather than from an event. */
  private continuous(state: SimState, previous: SimState): void {
    const p = state.player;

    // Footsteps, paced by distance covered rather than by a timer, so a sprint
    // is quicker feet and not the same feet played faster.
    if (p.stance === "grounded" || p.stance === "crouching") {
      this.stepPhase += Math.abs(p.x - previous.player.x);
      if (this.stepPhase > 34) {
        this.stepPhase = 0;
        this.hiss({ from: 900, to: 380, decay: 0.07, gain: 0.05, q: 0.9 });
      }
    } else {
      this.stepPhase = 30;
    }

    // A stroke each time the swimmer kicks, quieter and duller than a footstep
    // because it is happening through water.
    if (p.stance === "swimming" && Math.abs(p.x - previous.player.x) > 0.5) {
      this.stepPhase += Math.abs(p.x - previous.player.x);
      if (this.stepPhase > 46) {
        this.stepPhase = 0;
        this.hiss({ from: 320, to: 140, decay: 0.16, gain: 0.05, q: 0.6 });
      }
    }

    // Landing. Read off the velocity rather than an event because there is no
    // event for it — and a heavy landing should sound heavier.
    if (previous.player.vy > 6 && p.vy <= 0.5 && p.stance === "grounded") {
      const heavy = Math.min(1, previous.player.vy / 18);
      this.hiss({ from: 260, to: 90, decay: 0.1 + heavy * 0.1, gain: 0.06 + heavy * 0.1, q: 0.7 });
      this.tone({ from: 90 - heavy * 25, to: 45, decay: 0.12, gain: 0.08 * heavy, type: "sine" });
    }

    // A swing, on the frame the blade goes live.
    const kind = p.action.kind;
    if (kind && previous.player.action.kind !== kind) {
      if (kind === "attack")
        this.hiss({ from: 1800, to: 700, decay: 0.13, gain: 0.11, q: 1.6 });
      if (kind === "smash")
        this.tone({ from: 300, to: 60, decay: 0.22, gain: 0.14, type: "sawtooth" });
      if (kind === "stun") {
        this.tone({ from: 150, to: 70, decay: 0.2, gain: 0.13, type: "square" });
        this.hiss({ from: 500, to: 200, decay: 0.16, gain: 0.07 });
      }
      if (kind === "block")
        this.tone({ from: 700, to: 900, decay: 0.09, gain: 0.07, type: "triangle" });
    }

    // The dash: a short scrape that tells you the i-frames are live.
    if (p.dashTicks > 0 && previous.player.dashTicks === 0)
      this.hiss({ from: 1400, to: 300, decay: 0.2, gain: 0.09, q: 0.8 });

    // THE CLOCK. Under ten seconds the mask starts to tick, and it speeds up.
    // This is the one sound in the game that is doing design work rather than
    // decoration: the air is the whole tension and until now it was silent.
    if (state.entered && !state.god) {
      const seconds = state.air / 60;
      if (seconds < 10 && seconds > 0) {
        const gap = 180 + seconds * 82;
        if (this.throttled("tick", gap)) {
          const urgency = 1 - seconds / 10;
          this.tone({
            from: 620 + urgency * 260,
            decay: 0.05,
            gain: 0.05 + urgency * 0.09,
            type: "square",
          });
        }
      }
      // And the moment it starts burning at all.
      if (this.lastAir === Infinity && state.air < state.airCapacity)
        this.tone({ from: 220, to: 320, decay: 0.5, gain: 0.06, type: "sine" });
      this.lastAir = state.air;
    }

    // A bubble popping, once per bubble lost, which is the underwater clock.
    const bubbles = Math.ceil(p.breath / tuning.swim.bubbleTicks);
    const wasBubbles = Math.ceil(previous.player.breath / tuning.swim.bubbleTicks);
    if (bubbles < wasBubbles && bubbles >= 0) {
      this.tone({ from: 900 - bubbles * 90, to: 1500, decay: 0.09, gain: 0.09, type: "sine" });
      this.hiss({ from: 2200, to: 900, decay: 0.06, gain: 0.03 });
    }
    this.lastBreath = p.breath;
  }

  /**
   * Which monster the next `enemyHit` belongs to.
   *
   * The event carries a position and a damage figure but not a kind, and adding
   * one would be a change to the simulation's vocabulary for the benefit of the
   * speakers — so it is matched here instead, by finding whatever was closest to
   * where the blow landed. Wrong only if two different monsters are standing in
   * the same place, at which point nobody can tell what they are hearing anyway.
   */
  private hitKind: string = "enemy.goblin";

  private nearestKind(state: SimState, x: number, y: number): string {
    let best = "enemy.goblin";
    let closest = Infinity;
    for (const e of state.enemies) {
      const d = Math.abs(e.x - x) + Math.abs(e.y - y);
      if (d < closest) {
        closest = d;
        best = e.kind;
      }
    }
    return best;
  }

  private hurt(kind: string): void {
    const v = VOICE[kind] ?? VOICE["enemy.goblin"];
    this.tone({
      from: v.hit,
      to: v.hit * 0.55,
      decay: v.long ? 0.22 : 0.1,
      gain: 0.1,
      type: v.type,
    });
    this.hiss({ from: v.hit * 3, to: v.hit, decay: 0.1, gain: 0.08, q: 0.9 });
  }

  private died(kind: string): void {
    const v = VOICE[kind] ?? VOICE["enemy.goblin"];
    this.tone({
      from: v.die * 1.6,
      to: v.die * 0.4,
      decay: v.long ? 0.9 : 0.4,
      gain: 0.14,
      type: v.type,
      fat: true,
    });
    this.hiss({
      from: v.die * 4,
      to: v.die * 0.6,
      decay: v.long ? 0.8 : 0.35,
      gain: 0.09,
    });
  }

  /** The wind-up, heard. See `VOICE`. */
  private tell(kind: string): void {
    const v = VOICE[kind] ?? VOICE["enemy.goblin"];
    this.tone({
      from: v.tell * 0.7,
      to: v.tell,
      decay: v.long ? 0.36 : 0.18,
      gain: 0.09,
      type: v.type,
    });
  }

  /** One event, one noise. */
  private event(e: SimEvent, near: (x: number) => boolean): void {
    // Everything with a position is only heard if it happened nearby. A shark
    // biting somebody a screen and a half away is not a sound, it is confusion.
    const at = (e as { x?: number }).x;
    if (typeof at === "number" && !near(at)) return;

    switch (e.type) {
      // ------------------------------------------------------------- combat
      case "parry":
        // The best sound in the game, because it is the best moment in it.
        this.tone({ from: 1400, to: 2100, decay: 0.5, gain: 0.2, type: "triangle", fat: true });
        this.tone({ from: 2600, decay: 0.3, gain: 0.09, type: "sine", delay: 0.02 });
        this.hiss({ from: 4000, to: 1200, decay: 0.18, gain: 0.08 });
        break;
      case "guardHeld":
        this.tone({ from: 320, to: 200, decay: 0.14, gain: 0.12, type: "square" });
        this.hiss({ from: 1200, to: 400, decay: 0.1, gain: 0.06 });
        break;
      case "shieldRaised":
        this.tone({ from: 400, to: 900, decay: 0.4, gain: 0.1, type: "triangle", fat: true });
        break;
      case "shieldHeld":
        this.tone({ from: 1100, to: 700, decay: 0.16, gain: 0.08, type: "sine" });
        break;
      case "enemyHit":
        // The voice is chosen where the blow lands, so a crowd is legible: what
        // you just hit says what it was.
        this.hurt(this.hitKind);
        break;
      case "enemyDied":
        this.died(this.hitKind);
        break;
      case "playerHit":
        // Lower and wetter than hitting something else, so the two are never
        // confused in a crowd.
        this.tone({ from: 150, to: 70, decay: 0.3, gain: 0.16, type: "square", fat: true });
        this.hiss({ from: 400, to: 120, decay: 0.2, gain: 0.1 });
        break;

      // ---------------------------------------------------------- projectiles
      case "arrowLoosed":
        this.hiss({ from: 2600, to: 1400, decay: 0.1, gain: 0.07, q: 2 });
        break;
      case "arrowStruck":
        this.hiss({ from: 1600, to: 500, decay: 0.08, gain: 0.07, q: 1.4 });
        break;
      case "arrowReturned":
      case "fireballReturned":
        this.tone({ from: 1800, to: 2600, decay: 0.25, gain: 0.13, type: "triangle" });
        break;
      case "flameJet":
        if (this.throttled("jet", 140))
          this.hiss({ from: 800, to: 1600, decay: 0.3, gain: 0.07, q: 0.6 });
        break;
      case "eruptionCalled":
        this.tone({ from: 60, to: 30, decay: 0.7, gain: 0.12, type: "sawtooth" });
        break;
      case "eruptionFired":
        this.hiss({ from: 300, to: 1800, decay: 0.5, gain: 0.14, q: 0.5 });
        this.tone({ from: 120, to: 40, decay: 0.5, gain: 0.1, type: "square" });
        break;
      case "caughtFire":
        this.hiss({ from: 500, to: 2400, decay: 0.6, gain: 0.1, q: 0.5 });
        break;
      case "poisoned":
        this.tone({ from: 300, to: 140, decay: 0.6, gain: 0.09, type: "sine", fat: true });
        break;

      // ------------------------------------------------------------- the water
      case "splashed":
        this.hiss({ from: 300, to: 2600, decay: 0.28, gain: 0.16, q: 0.5 });
        this.tone({ from: 500, to: 180, decay: 0.2, gain: 0.06, type: "sine" });
        break;
      case "drowning":
        if (this.throttled("drown", 420)) {
          this.tone({ from: 220, to: 90, decay: 0.5, gain: 0.16, type: "sawtooth", fat: true });
          this.hiss({ from: 700, to: 200, decay: 0.4, gain: 0.1 });
        }
        break;

      // -------------------------------------------------------------- the run
      case "entered":
        this.tone({ from: 180, to: 90, decay: 1.4, gain: 0.12, type: "sine", fat: true });
        break;
      case "environmentChanged":
        // A threshold you hear, so the five places are five places.
        this.tone({ from: 300, to: 450, decay: 0.9, gain: 0.09, type: "triangle", fat: true });
        break;
      case "chestOpened":
        this.tone({ from: 700, decay: 0.12, gain: 0.1, type: "triangle" });
        this.tone({ from: 1050, decay: 0.16, gain: 0.09, type: "triangle", delay: 0.07 });
        this.tone({ from: 1400, decay: 0.4, gain: 0.09, type: "triangle", delay: 0.14 });
        break;
      case "lootDropped":
        this.tone({ from: 1600, to: 2200, decay: 0.16, gain: 0.06, type: "sine" });
        break;
      case "leverFlicked":
        // Heavy, mechanical, and final — it is permanent progress (FR-3.3).
        this.tone({ from: 220, to: 110, decay: 0.14, gain: 0.16, type: "square" });
        this.hiss({ from: 1800, to: 400, decay: 0.2, gain: 0.1, q: 1.2 });
        this.tone({ from: 70, decay: 0.7, gain: 0.1, type: "sine", delay: 0.1 });
        break;
      case "shortcutUsed":
      case "chuteEntered":
        this.hiss({ from: 400, to: 1800, decay: 0.5, gain: 0.1, q: 0.6 });
        break;
      case "chuteLaunched":
      case "geyserThrew":
      case "liftRode":
        this.tone({ from: 200, to: 1200, decay: 0.6, gain: 0.13, type: "triangle", fat: true });
        this.hiss({ from: 600, to: 2600, decay: 0.5, gain: 0.09, q: 0.5 });
        break;
      case "wallJumped":
        this.hiss({ from: 1100, to: 350, decay: 0.12, gain: 0.08, q: 1.1 });
        this.tone({ from: 300, to: 480, decay: 0.1, gain: 0.06, type: "triangle" });
        break;
      case "trapFired":
        this.tone({ from: 900, to: 200, decay: 0.2, gain: 0.14, type: "square" });
        break;
      case "thrownBack":
      case "fellThroughTheWorld":
        this.tone({ from: 400, to: 80, decay: 0.5, gain: 0.13, type: "sawtooth", fat: true });
        break;
      case "potionUsed":
        this.tone({ from: 600, to: 1500, decay: 0.45, gain: 0.12, type: "sine", fat: true });
        break;
      case "escaped":
        // Out, alive, and carrying it. Rising, and the only warm thing here.
        this.tone({ from: 400, to: 700, decay: 0.5, gain: 0.13, type: "triangle", fat: true });
        this.tone({ from: 600, to: 1000, decay: 0.7, gain: 0.1, type: "sine", delay: 0.16 });
        break;
      case "chamberEntered":
        this.tone({ from: 120, to: 55, decay: 1.8, gain: 0.16, type: "sawtooth", fat: true });
        this.hiss({ from: 200, to: 60, decay: 1.6, gain: 0.09, q: 0.6 });
        break;
      case "chamberLeft":
        this.tone({ from: 300, to: 500, decay: 0.8, gain: 0.1, type: "triangle" });
        break;
    }
  }
}