import Link from "next/link";

/**
 * The legal corner: the terms, who owns what, and where the privacy page is.
 *
 * A server component, because none of it moves. It is also deliberately SHORT —
 * the full terms live at `/terms` where they can be read and linked to, and
 * repeating them here in a smaller font would be two copies of a document that
 * must never disagree with itself.
 *
 * Written plainly rather than in the usual voice. Terms nobody can read are
 * terms nobody agreed to, and a free game made by one person does not need
 * eleven pages of it.
 */

const YEAR = 2026;

export default function LegalBox() {
  return (
    <div className="flex flex-col gap-4">
      <section className="flex flex-col gap-4 rounded-2xl border-2 border-rock-edge bg-rock/40 p-5">
        <div>
          <h2 className="font-mono text-sm font-black tracking-[0.2em] text-brass uppercase">
            The short version
          </h2>
          <p className="mt-1 text-xs leading-relaxed text-foreground/45">
            The full terms are one page and worth the two minutes. This is what
            they say.
          </p>
        </div>

        <ul className="flex flex-col divide-y divide-rock-edge/60">
          {[
            {
              t: "It is free, and there is nothing to buy",
              d: "No payment provider is connected to this game. Nobody can spend money here, so nobody can lose any.",
            },
            {
              t: "Your account is yours",
              d: "Ask and it is deleted, along with your runs and your save. You do not have to explain why.",
            },
            {
              t: "Play fairly",
              d: "Modifying the game to forge a score is the one thing that gets an account removed. Every ranked run is replayed by the server, so it is also the one thing least worth trying.",
            },
            {
              t: "It is in development",
              d: "Things change, break and occasionally get reset while the game is being built. Nothing here is promised to last forever.",
            },
          ].map((row) => (
            <li key={row.t} className="py-3">
              <p className="text-sm font-semibold text-foreground/90">{row.t}</p>
              <p className="mt-0.5 text-xs leading-relaxed text-foreground/45">
                {row.d}
              </p>
            </li>
          ))}
        </ul>

        <div className="flex flex-wrap gap-3">
          <Link
            href="/terms"
            className="rounded-full border-2 border-b-4 border-lens/50 bg-lens/10 px-4 py-1.5 font-mono text-[10px] font-black tracking-[0.16em] text-lens uppercase transition-transform hover:-translate-y-0.5 active:translate-y-0.5 active:border-b-2"
          >
            Read the terms
          </Link>
          <Link
            href="/privacy"
            className="rounded-full border-2 border-b-4 border-rock-edge px-4 py-1.5 font-mono text-[10px] font-black tracking-[0.16em] text-foreground/70 uppercase transition-transform hover:-translate-y-0.5 active:translate-y-0.5 active:border-b-2"
          >
            Privacy
          </Link>
        </div>
      </section>

      <section className="flex flex-col gap-3 rounded-2xl border-2 border-rock-edge bg-rock/40 p-5">
        <h2 className="font-mono text-sm font-black tracking-[0.2em] text-brass uppercase">
          Copyright
        </h2>
        <p className="font-mono text-sm text-foreground/85">
          © {YEAR} Khalid Aziz. All rights reserved.
        </p>
        <p className="text-xs leading-relaxed text-foreground/45">
          Air Debt, its name, its code, its artwork and its sound are the work of
          one person. <strong className="text-foreground/70">Every frame of art
          and every sound in this game was generated by scripts written for it</strong>
          {" "}— there is no licensed art, no stock audio and no asset pack in the
          project, which is why there is nobody else&apos;s licence to honour here.
        </p>
        <p className="text-xs leading-relaxed text-foreground/45">
          You are welcome to record it, stream it, and show it to people. You may
          not sell it, or ship a copy of it as your own.
        </p>
        <p className="text-xs leading-relaxed text-foreground/45">
          The game is built on open-source software — Next.js, React, PixiJS,
          Supabase and others — each used under its own licence and none of it
          claimed as mine.
        </p>
      </section>
    </div>
  );
}